include:
  -
    # include T000001 and all kits matching it somewhere on a segment of length >= 10cM
    id: T000001
    matches: 10
  -
    # include T000002 and all kits triangulating with it somewhere on a segment of length >= 8cM
    id: T000002
    triangles: 8
exclude: # these kits will be excluded from the clustering
  - T000003
  - T000004
min_length: 8.5 # only consider segments of length at least 8.5cM
tree:
  kits:
    -
      # me (male)
      id: T000001
      autox: true
      float: false
      negative: true
    -
      # my sister's son
      id: T000002
      float: false
  paternal:
    kits:
      -
        id: T000005 # my father's grand-niece
        float: false
      -
        id: T000006 # my father's sister (but not the grandmother of T000005)
        float: false
        negative: true
    paternal:
      kits:
        - T000007 # a distant cousin on my paternal grandfather's side
    maternal:
      # I don't know any relatives of my paternal grandmother, but I'd like any that are
      # discovered to be present in the output
  maternal:
    kits:
      - T000008 # a relative of my mother, but not my father, with no other information

# recommended to add matches and triangulations for T000001, T000002, T000006, and perhaps T000005
